runtime: python39

instance_class: F2

entrypoint: gunicorn -b :$PORT src.app:server

env_variables:
  PYTHON_VERSION: "3.9"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
